services:
  - type: web
    name: opencut-web
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon # Change to your preferred region (e.g., frankfurt, singapore)
    plan: free # Adjust based on your needs (free, standard, pro)
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://opencut:opencutthegoat@opencut-db:5432/opencut # Update after deployment
      - key: UPSTASH_REDIS_REST_URL
        fromService:
          name: opencut-redis
          type: redis
          property: connectionString
      - key: UPSTASH_REDIS_REST_TOKEN
        value: your-redis-token-here # Replace with actual token or set in Render dashboard
      - key: BETTER_AUTH_SECRET
        generateValue: true # Render will generate a secure random string
      - key: BETTER_AUTH_URL
        value: https://your-app-name.onrender.com # Replace with your Render app URL
    healthCheckPath: /health # Optional: Add a health check endpoint in your app
    autoDeploy: false # Set to true if you want automatic deploys on git push

  - type: pserv
    name: opencut-db
    env: docker
    region: oregon # Match the web service region
    plan: free # Adjust based on your needs
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_USER
        value: opencut
      - key: POSTGRES_PASSWORD
        value: opencutthegoat
      - key: POSTGRES_DB
        value: opencut
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10 # Adjust based on your needs

  - type: redis
    name: opencut-redis
    region: oregon # Match the web service region
    plan: free # Adjust based on your needs
    ipAllowList: [] # Allow access from web service
