services:
  - type: web
    name: opencut-web
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore # Match the database region (Singapore)
    plan: free # Explicitly set to free tier
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://opencut:XiklTaFY1Sf8W7QcLmaLQhTAHsN9XO0V@dpg-d1tf7mbuibrs73feiong-a/opencut # Internal connection string
      - key: redis://red-d1tffe2dbo4c73dhrn0g:6379
        fromService:
          name: opencut-redis
          type: redis
          property: connectionString
      - key: UPSTASH_REDIS_REST_TOKEN
        value: absolutesaygex69 # Replace with actual token or set in Render dashboard
      - key: BETTER_AUTH_SECRET
        generateValue: true # Render will generate a secure random string
      - key: BETTER_AUTH_URL
        value: https://your-app-name.onrender.com # Replace with your Render app URL
    healthCheckPath: /health # Optional: Add a health check endpoint in your app
    autoDeploy: false # Set to true if you want automatic deploys on git push

  - type: redis
    name: opencut-redis
    region: singapore # Match the database region (Singapore)
    plan: free # Explicitly set to free tier
    ipAllowList: [] # Allow access from web service
